pickup_lines = [
    "Are you a magician? Because whenever I look at you, everyone else disappears. 😉",
    "Do you have a name, or can I call you mine? 😘",
    "Is your name {name}? Because you've been running through my mind all day! 🏃‍♂️💖",
    "Are you French? Because Eiffel for you. 😍",
    "Do you have a map? I just got lost in your eyes. 🗺️❤️",
    "Are you WiFi? Because I'm feeling a connection. 📶💘",
    "Do you like Star Wars? Because Yoda one for me. 🌟💛",
    "I never believed in love at first sight, but that was before I saw you, {name}. 💖",
    "I must be lost, because heaven is a long way from here, and you look like an angel. 😇",
    "If kisses were stars, I’d give you the galaxy, {name}. 🌌💋",
    "They say the best things in life are free… Can I have a moment of your time? ⏳❤️",
    "Are you a sunset? Because I can’t take my eyes off you, {name}. 🌅😍",
    "Do you believe in fate? Because I think we were meant to meet, {name}. 💘",
    "Your smile must be a black hole, because I’m completely drawn into it. 🕳️✨",
    "I was writing a poem, but I got stuck… because nothing rhymes with your beauty, {name}. 📝💓",
    "You must be a magician because whenever you enter the room, everything else disappears. 🎩✨",
    "Can you lend me your hand? I just want to hold my future. 🤝❤️",
    "Your eyes are like the ocean—deep, endless, and impossible not to get lost in. 🌊💙",
    "I used to have a heart… but then you walked in and stole it, {name}. ❤️🔐",
    "Is it okay if I follow you home? Because my heart says you live there. 🏡💓",
    "I was having a bad day, but then I saw your smile, and everything changed. 😊☀️",
    "Do you hear that? It’s my heart skipping a beat every time you look at me, {name}. 💓🎶",
    "I don’t need a map, {name}, because I’m lost in your eyes. 🗺️💖",
    "You must be made of stardust, because you light up my entire world. ✨🌍",
    "I’d say God bless you, but it looks like He already did when He made you. 🙏💞",
    "Are you cold? Because I’d love to be the warmth in your arms. ❄️🔥",
    "Even if there was no gravity, I’d still fall for you, {name}. 🌍💘",
]
